package com.example.logcollector.model;

/**
 * DTO for the Log Analysis Response.
 * Contains the results of the intelligent search processing.
 * 
 * @param originalQuestion The original question asked by the user.
 * @param generatedSpl     The SPL query generated by the AI (Text-to-SPL).
 * @param aiSummary        The structured summary provided by the AI.
 */
public record LogAnalysisResponse(
                String originalQuestion,
                String generatedSpl,
                String aiSummary) {
}
